{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cryto-data-ext-ld-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cryto-data-ext-ld-secrets",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "API_KEY": "AgDFVLXV7tyQlyvNt7GbL19NOCrJd8hEUeV1HR8+klUljxbi+/jZt8E+MGxrREhZPYg8FFZudxOMWUPdRFXG7dpsjgCZbflnsPMKmduTKPhSlsNKb509Mv/GBO9A717lFWJ2GBb0nWD6uDq48vmt/gOT+GfKlFs7I1WyiNe2X+qPC2cLeu23WpMHWuUoysygN6eXGevwmE7diZuSy7b4kKio1/vonaSBQdVWXfe0YhEH1O1NMhhZ2YNEU1nCVr8C/Ao0fE2Mt04t9HmwerTpxF+wVOMEteLosnbyl9zMCXJfHdBsKrNzfWCVBfVz9HeP+bKNT3XNUMdveSsHf+Hm7FnnEQkv+k8ez+ocBgQV2jULhhzGt1+V2zMjjZvPIXMMYgyJNjpWxQQoWsq4JBjSNNY07e308Ta3QVRc1/NGjap/mWFdGm9PBLkcO3vF/4me4Ehi0mlRnD8NRsbiwMWu59Oyjv0vo72YlgS8b0SpVTyIrp/joUDs87Xod1MdycVf0+CMfdbZQarwlUSamhhGcDeWflORBZf7375gLfNsLjDmYH1eS/HYKK43v6xwgerlj9UUw2X/HGr90RrWh44J6gMYadqer0OwpfXiwfAGBhv+ZLy294vpMdYMqMWJ2q26og2JVY+6yOOzGppasf/JnCnmj6bl43ZpdbDMH2ZGRUZrBhY6xxsdMVauGfe0Eo3cVZ3XHc+ggGOncvCEh7a1WbkqMCi1CZILp0kf+0HoEawxQ6Kj21A18S7zjDIgu0305/vuAo3NGBei40LQi7SNMoCU",
      "API_SECRET": "AgCnZwDm0CvbWbL+Y8SycuN3Jgfp7rcziHlVv3k7CGbuLt9bWusPO0Nv0hqtnaxezp50mNkNR8EikGaKFpL11FcTGni3DDSoz/yw1ljVYbKzyWVCnq04RqBapvpPJgYyxggFdNkhypPwtd+9jre9R/f+GaDhes/03tG+u2i5b2wwioQDEuevgM/N4/N3MUx4WwBVv/WHGSZPBXQydyWtmvEH/ppZXJ1M0p5IfCDxf+Zeywb/nLvtRQZPy2KXnIzPjzr/lm1JAu0m5MeGI4ktQedIweiMrvf81OUkk8PMiZiubJhI37SsGUtEWyini+11eeWs7hIaJ3zaq0hbJynRhHoRz2QxWvHhHV+ChOhtlPL0dzkdFTRNuoerGgU9PY/M26SBCfX3PFf5v/td+Dp+FBdoi2lbJTRUxOxordYwLmEe1eYd2sxDh3luLz5JbAH6jryqazbmIaj3UB36e/N9gGzo9BX+ifmx8RIsBqh9iQTktWmGrsztdURl+Zaw/x1ZoCtMMbNPoaNUQCFjoQPfYETRADOWMRmAhhyHQf5RHJc7mpZYmFlfE1RR8hpkaMpCv4xY7pGJ8TrBpAPE3uvyVfKByquIA5VdLxYBzeacUEijGYVGI9ukb1D+WdHRRFads08a9wm1Pu+NUTz4COp7TkGzJP/eM0/AQfANR12A2aEI0MKFzxB56g6pvzpdWggQpDYJE7vB9OLSYXnBmQWkIcno3glRQbgrIFo94vnCU7xVZfmqI/OrwNWAPb+N3KA07rkm3hH2fqBBZ4L0uNWYOyJzmBeRrEAVk7Q="
    }
  }
}
